[build]
  command = "pnpm install --frozen-lockfile && pnpm build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = ".next,.netlify"
  SECRETS_SCAN_OMIT_KEYS = "NODE_ENV"

[[plugins]]
  package = "@netlify/plugin-nextjs"
