/**
 * Regenerates src/lib/event-types/generated.ts from the API's serializable
 * event-type registry (GET /event-types/config). The API is the single source
 * of truth for the config; this keeps the web mirror in lockstep.
 *
 * Usage: API_BASE_URL=http://localhost:3001 npx tsx scripts/sync-event-types.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const API_BASE_URL =
  process.env.API_BASE_URL ??
  process.env.NEXT_PUBLIC_API_BASE_URL ??
  "http://localhost:3001";

const OUT = join(process.cwd(), "src", "lib", "event-types", "generated.ts");

const main = async () => {
  const res = await fetch(`${API_BASE_URL}/api/v1/event-types/config`);
  if (!res.ok) {
    throw new Error(`Failed to fetch event-type config: ${res.status}`);
  }
  const body = (await res.json()) as {
    data: { eventTypes: unknown[] };
  };
  const configs = body.data.eventTypes;

  const contents =
    `// AUTO-GENERATED by scripts/sync-event-types.ts from the API GET /event-types/config.\n` +
    `// Do not edit by hand. Run \`npm run sync:event-types\` to regenerate.\n` +
    `import type { EventTypeConfig } from "./types";\n\n` +
    `export const EVENT_TYPE_CONFIGS: EventTypeConfig[] = ${JSON.stringify(
      configs,
      null,
      2,
    )};\n`;

  writeFileSync(OUT, contents);
  console.log(`Wrote ${configs.length} event-type configs to ${OUT}`);
};

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
